# -*- coding: utf-8 -*-
"""KG_visualisation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w4PIbueRo_JBoE-1KEWjRzMtMVFKxITw
"""


import json

filename ='/content/dse_kg (2).json'
data = json.load(open(filename))
data

import networkx as nx
from pyvis.network import Network

# Create PyVis network
net = Network(height="800px", width="100%", directed=True, bgcolor="#ffffff", font_color="black")

# Use a physics-enabled layout
net.barnes_hut()

# Initialize NetworkX graph
G = nx.DiGraph()

# Add nodes
for node in data["nodes"]:
    node_id = node["id"]
    title = f"""
    <b>{node.get('name','')}</b><br>
    Email: {node.get('email','')}<br>
    Dept: {node.get('department','')}<br>
    Position: {node.get('position','')}<br>
    Homepage: {node.get('homepage','')}
    """
    G.add_node(node_id, title=title, label=node.get("name", node_id))

# Add edges
for e in data["edges"]:
    G.add_edge(e["from"], e["to"], title=e["relation"], label=e["relation"])

# Build graph
net.from_nx(G)

from IPython.core.display import HTML

HTML(open("iiserb_graph.html", "r").read())

from google.colab import files
files.download("iiserb_graph.html")

